version: '3'
services:
  web:
    build: .
    volumes:
      - .:/var/www/html/programming-quiz2
    ports:
      - 8081:8081
      - 3000:3000
  database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DATABASE: quiz
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5434:5432